# Generated by Django 4.2.11 on 2026-06-18 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次编号')),
                ('material_type', models.CharField(choices=[('oak', '橡木'), ('pine', '松木'), ('bamboo', '竹材'), ('fruitwood', '果木'), ('mixed', '杂木'), ('other', '其他')], max_length=20, verbose_name='原料类型')),
                ('material_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原料重量(kg)')),
                ('charcoal_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成炭重量(kg)')),
                ('ignition_date', models.DateTimeField(verbose_name='点火日期')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='出窑日期')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '烧炭批次',
                'verbose_name_plural': '烧炭批次',
                'ordering': ['-ignition_date'],
            },
        ),
        migrations.CreateModel(
            name='Kiln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='窑号')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='所在位置')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='装窑容量(kg)')),
                ('build_date', models.DateField(blank=True, null=True, verbose_name='建造日期')),
                ('status', models.CharField(choices=[('active', '使用中'), ('idle', '闲置'), ('maintenance', '维修中'), ('retired', '报废')], default='idle', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '炭窑档案',
                'verbose_name_plural': '炭窑档案',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='窑温(℃)')),
                ('position', models.CharField(default='窑中心', max_length=50, verbose_name='测温位置')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_records', to='kiln_app.batch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '温度记录',
                'verbose_name_plural': '温度记录',
                'ordering': ['record_time'],
            },
        ),
        migrations.CreateModel(
            name='SmokeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('stage', models.CharField(choices=[('drying', '干燥期（白烟）'), ('precarbonization', '预炭化（黄烟）'), ('carbonization', '炭化期（青烟）'), ('refining', '精炼期（淡烟/无烟）'), ('cooling', '冷却期'), ('abnormal_heavy_smoke', '异常浓烟'), ('abnormal_no_smoke_early', '异常过早无烟'), ('abnormal_black_smoke', '异常黑烟')], max_length=30, verbose_name='烟色阶段')),
                ('smoke_density', models.IntegerField(blank=True, null=True, verbose_name='烟浓密度(1-10)')),
                ('is_normal', models.BooleanField(default=True, verbose_name='是否正常')),
                ('warning_message', models.CharField(blank=True, max_length=500, verbose_name='异常提示')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smokestage_set', to='kiln_app.batch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '烟色阶段记录',
                'verbose_name_plural': '烟色阶段记录',
                'ordering': ['record_time'],
            },
        ),
        migrations.CreateModel(
            name='KilnRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('excellent', '特级'), ('good', '一级'), ('medium', '二级'), ('poor', '三级'), ('reject', '等外品')], max_length=20, verbose_name='质量等级')),
                ('appearance_score', models.IntegerField(blank=True, null=True, verbose_name='外观评分(1-100)')),
                ('hardness_score', models.IntegerField(blank=True, null=True, verbose_name='硬度评分(1-100)')),
                ('moisture_score', models.IntegerField(blank=True, null=True, verbose_name='含水率评分(1-100)')),
                ('ash_content_score', models.IntegerField(blank=True, null=True, verbose_name='灰分评分(1-100)')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='综合评分')),
                ('evaluator', models.CharField(blank=True, max_length=50, verbose_name='评定人')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='评定日期')),
                ('remarks', models.TextField(blank=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='kiln_app.batch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '出窑评级',
                'verbose_name_plural': '出窑评级',
            },
        ),
        migrations.CreateModel(
            name='DamperRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('damper_opening', models.IntegerField(verbose_name='风门开度(%)')),
                ('damper_name', models.CharField(default='主风门', max_length=50, verbose_name='风门名称')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='调整原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damper_records', to='kiln_app.batch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '风门调整记录',
                'verbose_name_plural': '风门调整记录',
                'ordering': ['record_time'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='kiln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiln_app.kiln', verbose_name='炭窑'),
        ),
    ]
