# Generated by Django 4.2.11 on 2026-06-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiln_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_time', models.DateTimeField(verbose_name='预警时间')),
                ('warning_type', models.CharField(choices=[('stage_mismatch', '阶段不匹配'), ('temp_anomaly', '温度异常'), ('damper_anomaly', '风门异常'), ('combo_anomaly', '组合异常'), ('smoke_anomaly', '烟色异常')], max_length=30, verbose_name='预警类型')),
                ('level', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=20, verbose_name='预警级别')),
                ('detected_stage', models.CharField(blank=True, max_length=30, verbose_name='识别烧制阶段')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='当时窑温(℃)')),
                ('damper_opening', models.IntegerField(blank=True, null=True, verbose_name='当时风门开度(%)')),
                ('smoke_stage', models.CharField(blank=True, max_length=30, verbose_name='当时烟色阶段')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_warnings', to='kiln_app.batch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '工艺预警',
                'verbose_name_plural': '工艺预警',
                'ordering': ['-warning_time'],
            },
        ),
    ]
