# Generated by Django 4.2.11 on 2026-06-18 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiln_app', '0002_processwarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='原料批次号')),
                ('wood_species', models.CharField(choices=[('oak', '橡木'), ('pine', '松木'), ('bamboo', '竹材'), ('fruitwood', '果木'), ('birch', '桦木'), ('fir', '杉木'), ('mixed', '杂木'), ('other', '其他')], max_length=20, verbose_name='木材种类')),
                ('arrival_date', models.DateField(default=django.utils.timezone.now, verbose_name='到货日期')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='入库总重量(kg)')),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='初始含水率(%)')),
                ('piece_count', models.IntegerField(blank=True, null=True, verbose_name='根数/件数')),
                ('average_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='平均直径(cm)')),
                ('average_length', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='平均长度(cm)')),
                ('storage_location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('quality_grade', models.CharField(blank=True, choices=[('excellent', '特级'), ('good', '一级'), ('medium', '二级'), ('poor', '三级'), ('reject', '不合格')], max_length=20, null=True, verbose_name='质检等级')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='质检说明')),
                ('inspector', models.CharField(blank=True, max_length=50, verbose_name='检验员')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='检验日期')),
                ('storage_status', models.CharField(choices=[('in_stock', '在库'), ('partial_used', '部分领用'), ('used_up', '已用完'), ('discarded', '已报废')], default='in_stock', max_length=20, verbose_name='库存状态')),
                ('expected_shelf_life', models.IntegerField(default=90, verbose_name='保质期(天)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='单价(元/kg)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总成本(元)')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '原料批次',
                'verbose_name_plural': '原料批次',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('wood_species', models.CharField(blank=True, max_length=200, verbose_name='供应树种')),
                ('supply_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='月供应量(kg)')),
                ('status', models.CharField(choices=[('active', '合作中'), ('inactive', '暂停合作'), ('blacklisted', '黑名单')], default='active', max_length=20, verbose_name='合作状态')),
                ('credit_rating', models.IntegerField(blank=True, null=True, verbose_name='信用评分(1-100)')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商档案',
                'verbose_name_plural': '供应商档案',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('low_stock', '低库存预警'), ('expiring', '临期预警'), ('expired', '超期存放预警')], max_length=20, verbose_name='预警类型')),
                ('warning_level', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=20, verbose_name='预警级别')),
                ('warning_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预警时间')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前库存(kg)')),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预警阈值')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_by', models.CharField(blank=True, max_length=50, verbose_name='处理人')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='kiln_app.rawmaterialbatch', verbose_name='原料批次')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
                'ordering': ['-warning_date'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stock_in', '入库'), ('stock_out', '领料出库'), ('loss', '损耗'), ('adjust', '库存调整'), ('return', '退库')], max_length=20, verbose_name='交易类型')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量(kg)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='结存数量(kg)')),
                ('reference_no', models.CharField(blank=True, max_length=50, verbose_name='关联单号')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='kiln_app.rawmaterialbatch', verbose_name='原料批次')),
            ],
            options={
                'verbose_name': '库存台账',
                'verbose_name_plural': '库存台账',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_batches', to='kiln_app.supplier', verbose_name='供应商'),
        ),
        migrations.CreateModel(
            name='MoistureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
                ('moisture_content', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='检测含水率(%)')),
                ('test_method', models.CharField(default='快速水分测定仪', max_length=100, verbose_name='检测方法')),
                ('sample_location', models.CharField(blank=True, max_length=100, verbose_name='取样位置')),
                ('tester', models.CharField(blank=True, max_length=50, verbose_name='检测人')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moisture_tests', to='kiln_app.rawmaterialbatch', verbose_name='原料批次')),
            ],
            options={
                'verbose_name': '含水率检测记录',
                'verbose_name_plural': '含水率检测记录',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_no', models.CharField(max_length=50, unique=True, verbose_name='损耗单号')),
                ('loss_type', models.CharField(choices=[('natural', '自然损耗'), ('spoilage', '变质损坏'), ('damage', '人为损坏'), ('theft', '失窃'), ('other', '其他')], max_length=20, verbose_name='损耗类型')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='损耗重量(kg)')),
                ('loss_date', models.DateField(default=django.utils.timezone.now, verbose_name='损耗日期')),
                ('discovered_by', models.CharField(blank=True, max_length=50, verbose_name='发现人')),
                ('description', models.TextField(verbose_name='损耗原因说明')),
                ('handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='处理人')),
                ('handling_method', models.TextField(blank=True, verbose_name='处理方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='losses', to='kiln_app.rawmaterialbatch', verbose_name='原料批次')),
            ],
            options={
                'verbose_name': '损耗记录',
                'verbose_name_plural': '损耗记录',
                'ordering': ['-loss_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(max_length=50, unique=True, verbose_name='领料单号')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='领用重量(kg)')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='领料日期')),
                ('requester', models.CharField(blank=True, max_length=50, verbose_name='领料人')),
                ('stock_keeper', models.CharField(blank=True, max_length=50, verbose_name='发料人')),
                ('status', models.CharField(choices=[('pending', '待出库'), ('completed', '已出库'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='kiln_app.batch', verbose_name='烧炭批次')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='kiln_app.rawmaterialbatch', verbose_name='原料批次')),
            ],
            options={
                'verbose_name': '领料出库',
                'verbose_name_plural': '领料出库',
                'ordering': ['-issue_date'],
            },
        ),
    ]
