# Generated by Django 4.2.11 on 2026-06-19 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiln_app', '0004_batchcost_costwarning_purchasearrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiringRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配方名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='配方编号')),
                ('wood_species', models.CharField(choices=[('oak', '橡木'), ('pine', '松木'), ('bamboo', '竹材'), ('fruitwood', '果木'), ('birch', '桦木'), ('fir', '杉木'), ('mixed', '杂木'), ('other', '其他')], max_length=20, verbose_name='适用树种')),
                ('kiln_type', models.CharField(blank=True, max_length=100, verbose_name='适用窑型')),
                ('target_grade', models.CharField(choices=[('excellent', '特级'), ('good', '一级'), ('medium', '二级'), ('poor', '三级'), ('reject', '等外品')], default='good', max_length=20, verbose_name='目标等级')),
                ('target_yield_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目标出炭率(%)')),
                ('total_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='总烧制时长(小时)')),
                ('ignition_duration_minutes', models.IntegerField(default=30, verbose_name='点火时长(分钟)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='配方说明')),
                ('created_by', models.CharField(blank=True, max_length=50, verbose_name='创建人')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '烧制配方',
                'verbose_name_plural': '烧制配方',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_batches', models.IntegerField(default=0, verbose_name='总批次数')),
                ('completed_batches', models.IntegerField(default=0, verbose_name='完成批次数')),
                ('avg_yield_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='平均出炭率(%)')),
                ('avg_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均烧制时长(小时)')),
                ('total_deviations', models.IntegerField(default=0, verbose_name='总偏差次数')),
                ('severe_deviations', models.IntegerField(default=0, verbose_name='严重偏差次数')),
                ('excellent_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='特级品率(%)')),
                ('good_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='一级品率(%)')),
                ('avg_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='平均综合评分')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='最后计算时间')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='kiln_app.firingrecipe', verbose_name='所属配方')),
            ],
            options={
                'verbose_name': '配方统计',
                'verbose_name_plural': '配方统计',
            },
        ),
        migrations.CreateModel(
            name='RecipeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.IntegerField(verbose_name='阶段顺序')),
                ('stage_name', models.CharField(choices=[('ignition', '点火期'), ('drying', '干燥期'), ('precarbonization', '预炭化期'), ('carbonization', '炭化期'), ('refining', '精炼期'), ('cooling', '冷却期')], max_length=50, verbose_name='阶段名称')),
                ('duration_minutes', models.IntegerField(verbose_name='持续时长(分钟)')),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='最低温度(℃)')),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='最高温度(℃)')),
                ('temp_target', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='目标温度(℃)')),
                ('damper_min', models.IntegerField(default=0, verbose_name='风门最小开度(%)')),
                ('damper_max', models.IntegerField(default=100, verbose_name='风门最大开度(%)')),
                ('damper_target', models.IntegerField(blank=True, null=True, verbose_name='风门目标开度(%)')),
                ('smoke_color', models.CharField(blank=True, choices=[('white', '白烟'), ('yellow', '黄烟'), ('green', '青烟'), ('light', '淡烟'), ('none', '无烟'), ('black', '黑烟')], max_length=20, verbose_name='烟色')),
                ('operation_points', models.TextField(blank=True, verbose_name='操作要点')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='kiln_app.firingrecipe', verbose_name='所属配方')),
            ],
            options={
                'verbose_name': '配方阶段',
                'verbose_name_plural': '配方阶段',
                'ordering': ['recipe', 'stage_order'],
                'unique_together': {('recipe', 'stage_order')},
            },
        ),
        migrations.CreateModel(
            name='RecipeDeviationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('deviation_type', models.CharField(choices=[('temperature', '温度偏差'), ('damper', '风门偏差'), ('smoke', '烟色偏差'), ('timing', '时间偏差')], max_length=20, verbose_name='偏差类型')),
                ('deviation_level', models.CharField(choices=[('normal', '正常'), ('slight', '轻微偏差'), ('moderate', '中等偏差'), ('severe', '严重偏差')], default='normal', max_length=20, verbose_name='偏差级别')),
                ('standard_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='标准值')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际值')),
                ('deviation_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='偏差值')),
                ('deviation_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='偏差率(%)')),
                ('description', models.TextField(blank=True, verbose_name='偏差描述')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_by', models.CharField(blank=True, max_length=50, verbose_name='处理人')),
                ('resolved_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_deviations', to='kiln_app.batch', verbose_name='所属批次')),
                ('recipe_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiln_app.recipestage', verbose_name='对应配方阶段')),
            ],
            options={
                'verbose_name': '配方偏差记录',
                'verbose_name_plural': '配方偏差记录',
                'ordering': ['-record_time'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='current_recipe_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_batches', to='kiln_app.recipestage', verbose_name='当前配方阶段'),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='kiln_app.firingrecipe', verbose_name='套用配方'),
        ),
    ]
